---
version: '3'
services:
  broker:
    image: wurstmeister/kafka
    hostname: broker
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: broker
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - smooth-streaming_app-tier
networks:
  smooth-streaming_app-tier:
    external: true